=== oneliang/frame-golang/transfer/database_transfer/config/transfer.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT transfer (fromTable, toTable)>
<!ELEMENT fromTable (mainTable, slaveTable*)>
<!ELEMENT mainTable (column*)>
<!ATTLIST mainTable name CDATA #REQUIRED>
<!ATTLIST mainTable sequenceKey CDATA #REQUIRED>
<!ELEMENT slaveTable (column*)>
<!ATTLIST slaveTable name CDATA #REQUIRED>
<!ATTLIST slaveTable mergeKeys CDATA #REQUIRED>
<!ELEMENT column EMPTY>
<!ATTLIST column name CDATA #REQUIRED>
<!ATTLIST column dataKey CDATA #REQUIRED>
<!ELEMENT toTable (toColumn*)>
<!ATTLIST toTable name CDATA #REQUIRED>
<!ATTLIST toTable comment CDATA #IMPLIED>
<!ELEMENT toColumn EMPTY>
<!ATTLIST toColumn dataKey CDATA #REQUIRED>
<!ATTLIST toColumn name CDATA #REQUIRED>
<!ATTLIST toColumn databaseType (varchar|int|float|datetime) #REQUIRED>
<!ATTLIST toColumn length CDATA #IMPLIED>
<!ATTLIST toColumn precision CDATA #IMPLIED>
<!ATTLIST toColumn nullable (false|true) #IMPLIED>
<!ATTLIST toColumn defaultValue CDATA #IMPLIED>
<!ATTLIST toColumn comment CDATA #IMPLIED>

=== oneliang/frame-golang/transfer/database_transfer/config/transfer.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE transfer SYSTEM "transfer.dtd">
<transfer>
    <fromTable>
        <mainTable name="t_module" sequenceKey="id">
            <column name="id" dataKey="id"/>
            <column name="name" dataKey="name"/>
            <column name="project_id" dataKey="project_id"/>
            <column name="create_time" dataKey="create_time"/>
        </mainTable>
    </fromTable>
    <toTable name="t_module_copy" comment="copy">
        <toColumn dataKey="name" name="name" databaseType="varchar" length="20" defaultValue="" comment="名字"/>
        <toColumn dataKey="project_id" name="project_id" databaseType="int" length="10" defaultValue="0" comment="项目Id"/>
        <toColumn dataKey="create_time" name="create_time" databaseType="datetime" length="3" defaultValue="1970-01-01 00:00:00" comment="创建时间"/>
    </toTable>

</transfer>
